# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bjørnar Dalsnes
email: bjornar.dalsnes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My programming projects.
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brdalsnes.github.io" # the base hostname & protocol for your site

#sidebar
#default-image: python_logo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

#built-by: Bjørnar Dalsnes

#copyright:
#   name: webjeda
#   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus: yes
disqus-shortname: webjeda-demo

#social
email: bjornar.dalsnes@gmail.com
github: http://github.com/brdalsnes
linkedin: https://www.linkedin.com/in/bjornar-dalsnes-103794140


#facebook like box
#fb-like-box: yes
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/webjeda/
#fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

